### ISSUE TITLE
Initial login by viewer brings them to /collections

### ISSUE THREAD

**Issue by emmello** [mitodl/odl-video-service#231] opened 2017-09-13 15:34 UTC
Viewer is given a link to view in OVS or a collection level link - user logs into OVS via Touchstone and is directed to their own page which shows up as blank.  As they have no access to view available collections, they think they don't have access to the videos.  Once logged in, if they try the link again it works, but usually viewers haven't been trying that as they think its broken.

It would be preferable to allow viewers to have access to any collection they have view access to, or the system redirects them to the original URL after login.

**Comment by Ferdi** [comment] 2017-09-21 18:25
@gsidebo are we still working on this ?

**Comment by gsidebo** [comment] 2017-09-21 18:26
Yes. Attempted fix didn't work out in production so we rolled it back. I'm going to meet with @shaidar to discuss the plan to test alternate fixes for this

**Comment by gsidebo** [comment] 2017-11-02 18:59
We've discovered that the source of the problem is that only the root route of the app (`/`) is configured in nginx with the necessary shibboleth settings. If a user is redirected to some other URL after logging in via shibboleth (e.g.: `/collections/12345/`), nginx is not configured to add the appropriate request headers, etc. When the user returns to the app without the correct request headers, they are considered anonymous by our middleware, then redirected back through shibboleth, which considers the user logged in (since they have an active) session, and in turn redirects _back_ to the app, resulting in the redirect loop. The fix for this will involve changing the nginx config. 

Configuring all app routes with the shibboleth settings (i.e.: using `location /` instead of `location =/`) fixes the bug, but that might not be optimal.

**Closed** 2017-11-08 02:12 UTC
Labels: bug
