### ISSUE TITLE
Allow users to edit edX course id for collection in UI

### ISSUE THREAD

**Issue by gsidebo** [mitodl/odl-video-service#764] opened 2019-08-01 17:46 UTC
PR #763 adds a feature where HLS-encoded video files are added to edX via HTTP API call. This depends on the video file's collection having an `edx_course_id` value to indicate the course that the videos should be added to. This value is not editable in the UI yet, so it has to be set in Django admin et al. We should add a course id field to the forms for adding/editing a collection so the collection owners can easily set that value.

**Comment by pdpinch** [comment] 2020-08-18 12:05
duplicate of #830 

closed by #835

**Comment by pdpinch** [comment] 2020-08-18 12:05
duplicate of #830 

closed by #835

**Closed by pdpinch** 2020-08-18 12:05 UTC
