### ISSUE TITLE
Analytics no longer showing on OVS videos

### ISSUE THREAD

**Issue by emmello** [mitodl/odl-video-service#658] opened 2018-06-28 15:05 UTC
Sometime after the semester ended, GA stopped reporting to OVS.:

![image](https://user-images.githubusercontent.com/1099800/42042693-c0ca604c-7ac2-11e8-83ca-a6471f500727.png)

Analytics are still being logged in GA.

**Comment by pdpinch** [comment] 2018-07-03 13:20
probably caused by #657

**Comment by pdpinch** [comment] 2018-07-06 15:51
Sentry issue: [ODL-VIDEO-SERVICE-60](https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/528140533/)

**Comment by pdpinch** [comment] 2018-07-06 15:52
Oops. Wrong Sentry issue.

**Comment by mbertrand** [comment] 2018-07-17 14:18
`GA_KEYFILE_JSON` was being stripped of double-quotes on deployment, fixed now.

**Closed by mbertrand** 2018-07-17 14:18 UTC
Labels: bug
